// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using server.src.Persistence.Common.Contexts;

#nullable disable

namespace Persistence.Migrations.Data
{
    [DbContext(typeof(DataContext))]
    [Migration("20250306092543_InitialCreate_data")]
    partial class InitialCreate_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("server.src.Domain.Auth.Permissions.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LockedByUserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("server.src.Domain.Auth.Roles.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserLockedId");

                    b.HasIndex("Id", "Name", "Description", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                Role_\r                Id_\r                Name_\r                Description_\r                IsActive");

                    b.ToTable("Roles", "auth");
                });

            modelBuilder.Entity("server.src.Domain.Auth.UserClaims.Models.UserClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "auth");
                });

            modelBuilder.Entity("server.src.Domain.Auth.UserLogins.Models.UserLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Id", "LoginProvider", "ProviderDisplayName", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                UserLogin_\r                Id_\r                LoginProvider_\r                ProviderDisplayName_\r                Date");

                    b.ToTable("UserLogins", "auth");
                });

            modelBuilder.Entity("server.src.Domain.Auth.UserLogouts.Models.UserLogout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Id", "LoginProvider", "ProviderDisplayName", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                UserLogout_\r                Id_\r                LoginProvider_\r                ProviderDisplayName_\r                Date");

                    b.ToTable("UserLogouts", "auth");
                });

            modelBuilder.Entity("server.src.Domain.Auth.UserRoles.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("Id", "UserId", "RoleId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                UserRole_\r                Id_\r                UserId_\r                RoleId_\r                Date");

                    b.ToTable("UserRoles", "auth");
                });

            modelBuilder.Entity("server.src.Domain.Auth.Users.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InitialPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MobilePhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("MobilePhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TwoFactorToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("TwoFactorTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserLockedId");

                    b.HasIndex("Id", "FirstName", "LastName", "Email", "UserName", "PhoneNumber", "MobilePhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                User_\r                Id_\r                FirstName_\r                LastName_\r                Email_\r                UserName_\r                PhoneNumber_\r                MobilePhoneNumber");

                    b.ToTable("Users", "auth");
                });

            modelBuilder.Entity("server.src.Domain.Developer.Actions.Models.Action", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("LockedByUserId");

                    b.ToTable("Action");
                });

            modelBuilder.Entity("server.src.Domain.Developer.Aggreggates.Models.Aggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LockedByUserId");

                    b.HasIndex("PermissionId");

                    b.ToTable("Aggregate");
                });

            modelBuilder.Entity("server.src.Domain.Developer.Features.Models.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LockedByUserId");

                    b.HasIndex("ModuleId");

                    b.ToTable("Feature");
                });

            modelBuilder.Entity("server.src.Domain.Developer.Modules.Models.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId");

                    b.HasIndex("LockedByUserId");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.Continents.Models.Continent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserLockedId");

                    b.HasIndex("Id", "Name", "Code", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                Continent_\r                Id_\r                Name_\r                Code_\r                IsActive");

                    b.ToTable("Continents", "geography_administrative");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.Countries.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AreaKm2")
                        .HasColumnType("double precision");

                    b.Property<string>("Capital")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Guid>("ContinentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContinentId");

                    b.HasIndex("UserLockedId");

                    b.HasIndex("Id", "Name", "Code", "Population", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                Country_\r                Id_\r                Name_\r                Code_\r                Population_\r                IsActive");

                    b.ToTable("Countries", "geography_administrative");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.Districts.Models.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MunicipalityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("UserLockedId");

                    b.HasIndex("Id", "Name", "Population", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                District_\r                Id_\r                Name_\r                Population_\r                IsActive");

                    b.ToTable("Districts", "geography_administrative");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.Municipalities.Models.Municipality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("UserLockedId");

                    b.HasIndex("Id", "Name", "Population", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                Municipality_\r                Id_\r                Name_\r                Population_\r                IsActive");

                    b.ToTable("Municipalities", "geography_administrative");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.Neighborhoods.Models.Neighborhood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("UserLockedId");

                    b.HasIndex("Id", "Name", "Zipcode", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                Neighborhood_\r                Id_\r                Name_\r                Zipcode_\r                IsActive");

                    b.ToTable("Neighborhoods", "geography_administrative");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.Regions.Models.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AreaKm2")
                        .HasColumnType("double precision");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.HasIndex("UserLockedId");

                    b.HasIndex("Id", "Name", "AreaKm2", "Code", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                Region_\r                Id_\r                Name_\r                AreaKm2_\r                Code_\r                IsActive");

                    b.ToTable("Regions", "geography_administrative");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.States.Models.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AreaKm2")
                        .HasColumnType("double precision");

                    b.Property<string>("Capital")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("UserLockedId");

                    b.HasIndex("Id", "Name", "Population", "Code", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                State_\r                Id_\r                Name_\r                Population_\r                Code_\r                IsActive");

                    b.ToTable("States", "geography_administrative");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Natural.ClimateZones.Models.ClimateZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AvgPrecipitationMm")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgTemperatureC")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LockedByUserId");

                    b.HasIndex("Id", "Name", "AvgTemperatureC", "AvgPrecipitationMm", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                ClimateZone_\r                Id_\r                Name_\r                AvgTemperatureC_\r                AvgPrecipitationMm_\r                IsActive");

                    b.ToTable("ClimateZone", "geography_natural");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Natural.Locations.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ClimateZoneId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uuid");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<Guid>("NaturalFeatureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NeighborhoodId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TerrainTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimezoneId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClimateZoneId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_Location_Id");

                    b.HasIndex("LockedByUserId");

                    b.HasIndex("NaturalFeatureId");

                    b.HasIndex("NeighborhoodId");

                    b.HasIndex("TerrainTypeId");

                    b.HasIndex("TimezoneId");

                    b.HasIndex("Id", "Longitude", "Latitude", "Altitude", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                Location_\r                Id_\r                Longitude_\r                Latitude_\r                Altitude_\r                IsActive");

                    b.ToTable("Locations", "geography_natural");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Natural.NaturalFeatures.Models.NaturalFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LockedByUserId");

                    b.ToTable("NaturalFeature");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Natural.TerrainTypes.Models.TerrainType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LockedByUserId");

                    b.HasIndex("Id", "Name", "Description", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                TerrainType_\r                Id_\r                Name_\r                Description_\r                IsActive");

                    b.ToTable("TerrainTypes", "geography_natural");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Natural.Timezones.Models.Timezone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("DstOffset")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("SupportsDaylightSaving")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<double>("UtcOffset")
                        .HasColumnType("double precision");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LockedByUserId");

                    b.HasIndex("Id", "Name", "UtcOffset", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                Timezone_\r                Id_\r                Name_\r                UtcOffset_\r                IsActive");

                    b.ToTable("TimeZones", "geography_natural");
                });

            modelBuilder.Entity("server.src.Domain.Metrics.AuditLogs.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdditionalMetadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("AfterValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeValues")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IsSystemAction")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TelemetryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TelemetryId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", "metrics");
                });

            modelBuilder.Entity("server.src.Domain.Metrics.LogErrors.Models.LogError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Instance")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Id", "Error", "StatusCode", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                LogError_\r                Id_\r                Error_\r                StatusCode_\r                Timestamp");

                    b.ToTable("LogErrors", "metrics");
                });

            modelBuilder.Entity("server.src.Domain.Metrics.Stories.Story", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SourceTelemetryRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetTelemetryRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TelemetryRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceTelemetryRecordId");

                    b.HasIndex("TargetTelemetryRecordId");

                    b.HasIndex("TelemetryRecordId");

                    b.HasIndex("UserId");

                    b.ToTable("Stories", "metrics");
                });

            modelBuilder.Entity("server.src.Domain.Metrics.TelemetryRecords.Models.TelemetryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CPUusage")
                        .HasColumnType("double precision");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("MemoryUsed")
                        .HasColumnType("bigint");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RequestBodySize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RequestTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ResponseBodySize")
                        .HasColumnType("bigint");

                    b.Property<long>("ResponseTime")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ResponseTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Id", "Method", "Path", "StatusCode", "ResponseTime", "RequestTimestamp")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                TelemetryRecord_\r                Id_\r                Method_\r                StatusCode_\r                ResponseTime_\r                RequestTimestamp");

                    b.ToTable("TelemetryRecords", "metrics");
                });

            modelBuilder.Entity("server.src.Domain.Metrics.Trails.Trail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuditLogId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceAuditLogId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetAuditLogId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuditLogId");

                    b.HasIndex("SourceAuditLogId");

                    b.HasIndex("TargetAuditLogId");

                    b.ToTable("Trails", "metrics");
                });

            modelBuilder.Entity("server.src.Domain.Weather.Forecasts.Models.Forecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AirQualityIndex")
                        .HasColumnType("integer");

                    b.Property<int>("CloudCover")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FeelsLikeC")
                        .HasColumnType("integer");

                    b.Property<int>("Humidity")
                        .HasColumnType("integer");

                    b.Property<int>("LightningProbability")
                        .HasColumnType("integer");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MoonPhaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("PollenCount")
                        .HasColumnType("integer");

                    b.Property<double>("PrecipitationMm")
                        .HasColumnType("double precision");

                    b.Property<double>("PressureHpa")
                        .HasColumnType("double precision");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeSpan>("Sunrise")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("Sunset")
                        .HasColumnType("interval");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("UVIndex")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.Property<double>("VisibilityKm")
                        .HasColumnType("double precision");

                    b.Property<Guid>("WarningId")
                        .HasColumnType("uuid");

                    b.Property<int>("WindDirection")
                        .HasColumnType("integer");

                    b.Property<double>("WindSpeedKph")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("MoonPhaseId");

                    b.HasIndex("UserLockedId");

                    b.HasIndex("WarningId");

                    b.HasIndex("Id", "Date", "TemperatureC", "Humidity")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                Forecast_\r                Id_\r                Date_\r                TemperatureC_\r                Humidity");

                    b.ToTable("Forecasts", "weather");
                });

            modelBuilder.Entity("server.src.Domain.Weather.MoonPhases.Models.MoonPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("DurationDays")
                        .HasColumnType("double precision");

                    b.Property<double>("IlluminationPercentage")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSignificant")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OccurrenceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PhaseOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserLockedId");

                    b.HasIndex("Id", "Name", "Description")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                MoonPhase_\r                Id_\r                Name_\r                Description");

                    b.ToTable("MoonPhases", "weather");
                });

            modelBuilder.Entity("server.src.Domain.Weather.Observations.Models.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AirQualityIndex")
                        .HasColumnType("integer");

                    b.Property<int>("CloudCover")
                        .HasColumnType("integer");

                    b.Property<int>("Humidity")
                        .HasColumnType("integer");

                    b.Property<int>("LightningProbability")
                        .HasColumnType("integer");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MoonPhaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("PollenCount")
                        .HasColumnType("integer");

                    b.Property<double>("PrecipitationMm")
                        .HasColumnType("double precision");

                    b.Property<double>("PressureHpa")
                        .HasColumnType("double precision");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UVIndex")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.Property<double>("VisibilityKm")
                        .HasColumnType("double precision");

                    b.Property<int>("WindDirection")
                        .HasColumnType("integer");

                    b.Property<double>("WindSpeedKph")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("MoonPhaseId");

                    b.HasIndex("UserLockedId");

                    b.HasIndex("Id", "Timestamp", "TemperatureC", "Humidity")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                Observation_\r                Id_\r                Timestamp_\r                TemperatureC_\r                Humidity");

                    b.ToTable("Observations", "weather");
                });

            modelBuilder.Entity("server.src.Domain.Weather.Warnings.Models.Warning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LockedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RecommendedActions")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserLockedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Version")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LockedByUserId");

                    b.HasIndex("Id", "Name", "Description")
                        .IsUnique()
                        .HasDatabaseName("IX_\r                Warning_\r                Id_\r                Name_\r                Description");

                    b.ToTable("Warnings", "weather");
                });

            modelBuilder.Entity("server.src.Domain.Auth.Permissions.Models.Permission", b =>
                {
                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("LockedByUserId");

                    b.HasOne("server.src.Domain.Auth.Roles.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LockedByUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("server.src.Domain.Auth.Roles.Models.Role", b =>
                {
                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("UserLockedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LockedByUser");
                });

            modelBuilder.Entity("server.src.Domain.Auth.UserClaims.Models.UserClaim", b =>
                {
                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.src.Domain.Auth.UserLogins.Models.UserLogin", b =>
                {
                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "User")
                        .WithMany("UserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.src.Domain.Auth.UserLogouts.Models.UserLogout", b =>
                {
                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "User")
                        .WithMany("UserLogouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.src.Domain.Auth.UserRoles.Models.UserRole", b =>
                {
                    b.HasOne("server.src.Domain.Auth.Roles.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.src.Domain.Auth.Users.Models.User", b =>
                {
                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("UserLockedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LockedByUser");
                });

            modelBuilder.Entity("server.src.Domain.Developer.Actions.Models.Action", b =>
                {
                    b.HasOne("server.src.Domain.Developer.Features.Models.Feature", "Feature")
                        .WithMany("Actions")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("LockedByUserId");

                    b.Navigation("Feature");

                    b.Navigation("LockedByUser");
                });

            modelBuilder.Entity("server.src.Domain.Developer.Aggreggates.Models.Aggregate", b =>
                {
                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("LockedByUserId");

                    b.HasOne("server.src.Domain.Auth.Permissions.Models.Permission", null)
                        .WithMany("Aggregates")
                        .HasForeignKey("PermissionId");

                    b.Navigation("LockedByUser");
                });

            modelBuilder.Entity("server.src.Domain.Developer.Features.Models.Feature", b =>
                {
                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("LockedByUserId");

                    b.HasOne("server.src.Domain.Developer.Modules.Models.Module", null)
                        .WithMany("Features")
                        .HasForeignKey("ModuleId");

                    b.Navigation("LockedByUser");
                });

            modelBuilder.Entity("server.src.Domain.Developer.Modules.Models.Module", b =>
                {
                    b.HasOne("server.src.Domain.Developer.Aggreggates.Models.Aggregate", "Aggregate")
                        .WithMany("Modules")
                        .HasForeignKey("AggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("LockedByUserId");

                    b.Navigation("Aggregate");

                    b.Navigation("LockedByUser");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.Continents.Models.Continent", b =>
                {
                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("UserLockedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LockedByUser");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.Countries.Models.Country", b =>
                {
                    b.HasOne("server.src.Domain.Geography.Administrative.Continents.Models.Continent", "Continent")
                        .WithMany("Countries")
                        .HasForeignKey("ContinentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("UserLockedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Continent");

                    b.Navigation("LockedByUser");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.Districts.Models.District", b =>
                {
                    b.HasOne("server.src.Domain.Geography.Administrative.Municipalities.Models.Municipality", "Municipality")
                        .WithMany("Districts")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("UserLockedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LockedByUser");

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.Municipalities.Models.Municipality", b =>
                {
                    b.HasOne("server.src.Domain.Geography.Administrative.Regions.Models.Region", "Region")
                        .WithMany("Municipalities")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("UserLockedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LockedByUser");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.Neighborhoods.Models.Neighborhood", b =>
                {
                    b.HasOne("server.src.Domain.Geography.Administrative.Districts.Models.District", "District")
                        .WithMany("Neighborhoods")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("UserLockedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("District");

                    b.Navigation("LockedByUser");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.Regions.Models.Region", b =>
                {
                    b.HasOne("server.src.Domain.Geography.Administrative.States.Models.State", "State")
                        .WithMany("Regions")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("UserLockedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LockedByUser");

                    b.Navigation("State");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.States.Models.State", b =>
                {
                    b.HasOne("server.src.Domain.Geography.Administrative.Countries.Models.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("UserLockedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Country");

                    b.Navigation("LockedByUser");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Natural.ClimateZones.Models.ClimateZone", b =>
                {
                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("LockedByUserId");

                    b.Navigation("LockedByUser");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Natural.Locations.Models.Location", b =>
                {
                    b.HasOne("server.src.Domain.Geography.Natural.ClimateZones.Models.ClimateZone", "ClimateZone")
                        .WithMany("Locations")
                        .HasForeignKey("ClimateZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("LockedByUserId");

                    b.HasOne("server.src.Domain.Geography.Natural.NaturalFeatures.Models.NaturalFeature", "NaturalFeature")
                        .WithMany("Locations")
                        .HasForeignKey("NaturalFeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.src.Domain.Geography.Administrative.Neighborhoods.Models.Neighborhood", "Neighborhood")
                        .WithMany("Locations")
                        .HasForeignKey("NeighborhoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.src.Domain.Geography.Natural.TerrainTypes.Models.TerrainType", "TerrainType")
                        .WithMany("Locations")
                        .HasForeignKey("TerrainTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.src.Domain.Geography.Natural.Timezones.Models.Timezone", "Timezone")
                        .WithMany("Locations")
                        .HasForeignKey("TimezoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClimateZone");

                    b.Navigation("LockedByUser");

                    b.Navigation("NaturalFeature");

                    b.Navigation("Neighborhood");

                    b.Navigation("TerrainType");

                    b.Navigation("Timezone");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Natural.NaturalFeatures.Models.NaturalFeature", b =>
                {
                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("LockedByUserId");

                    b.Navigation("LockedByUser");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Natural.TerrainTypes.Models.TerrainType", b =>
                {
                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("LockedByUserId");

                    b.Navigation("LockedByUser");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Natural.Timezones.Models.Timezone", b =>
                {
                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("LockedByUserId");

                    b.Navigation("LockedByUser");
                });

            modelBuilder.Entity("server.src.Domain.Metrics.AuditLogs.Models.AuditLog", b =>
                {
                    b.HasOne("server.src.Domain.Metrics.TelemetryRecords.Models.TelemetryRecord", "TelemetryRecord")
                        .WithMany("AuditLogs")
                        .HasForeignKey("TelemetryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TelemetryRecord");

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.src.Domain.Metrics.LogErrors.Models.LogError", b =>
                {
                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "User")
                        .WithMany("LogErrors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.src.Domain.Metrics.Stories.Story", b =>
                {
                    b.HasOne("server.src.Domain.Metrics.TelemetryRecords.Models.TelemetryRecord", "SourceTelemetryRecord")
                        .WithMany()
                        .HasForeignKey("SourceTelemetryRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("server.src.Domain.Metrics.TelemetryRecords.Models.TelemetryRecord", "TargetTelemetryRecord")
                        .WithMany()
                        .HasForeignKey("TargetTelemetryRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("server.src.Domain.Metrics.TelemetryRecords.Models.TelemetryRecord", null)
                        .WithMany("Stories")
                        .HasForeignKey("TelemetryRecordId");

                    b.HasOne("server.src.Domain.Auth.Users.Models.User", null)
                        .WithMany("Stories")
                        .HasForeignKey("UserId");

                    b.Navigation("SourceTelemetryRecord");

                    b.Navigation("TargetTelemetryRecord");
                });

            modelBuilder.Entity("server.src.Domain.Metrics.TelemetryRecords.Models.TelemetryRecord", b =>
                {
                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "User")
                        .WithMany("TelemetryRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.src.Domain.Metrics.Trails.Trail", b =>
                {
                    b.HasOne("server.src.Domain.Metrics.AuditLogs.Models.AuditLog", null)
                        .WithMany("Trails")
                        .HasForeignKey("AuditLogId");

                    b.HasOne("server.src.Domain.Metrics.AuditLogs.Models.AuditLog", "SourceAuditLog")
                        .WithMany()
                        .HasForeignKey("SourceAuditLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("server.src.Domain.Metrics.AuditLogs.Models.AuditLog", "TargetAuditLog")
                        .WithMany()
                        .HasForeignKey("TargetAuditLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceAuditLog");

                    b.Navigation("TargetAuditLog");
                });

            modelBuilder.Entity("server.src.Domain.Weather.Forecasts.Models.Forecast", b =>
                {
                    b.HasOne("server.src.Domain.Geography.Natural.Locations.Models.Location", "Location")
                        .WithMany("Forecasts")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.src.Domain.Weather.MoonPhases.Models.MoonPhase", "MoonPhase")
                        .WithMany("Forecasts")
                        .HasForeignKey("MoonPhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("UserLockedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("server.src.Domain.Weather.Warnings.Models.Warning", "Warning")
                        .WithMany("Forecasts")
                        .HasForeignKey("WarningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("LockedByUser");

                    b.Navigation("MoonPhase");

                    b.Navigation("Warning");
                });

            modelBuilder.Entity("server.src.Domain.Weather.MoonPhases.Models.MoonPhase", b =>
                {
                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("UserLockedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LockedByUser");
                });

            modelBuilder.Entity("server.src.Domain.Weather.Observations.Models.Observation", b =>
                {
                    b.HasOne("server.src.Domain.Geography.Natural.Locations.Models.Location", "Location")
                        .WithMany("Observation")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.src.Domain.Weather.MoonPhases.Models.MoonPhase", "MoonPhase")
                        .WithMany("Observations")
                        .HasForeignKey("MoonPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("UserLockedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Location");

                    b.Navigation("LockedByUser");

                    b.Navigation("MoonPhase");
                });

            modelBuilder.Entity("server.src.Domain.Weather.Warnings.Models.Warning", b =>
                {
                    b.HasOne("server.src.Domain.Auth.Users.Models.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("LockedByUserId");

                    b.Navigation("LockedByUser");
                });

            modelBuilder.Entity("server.src.Domain.Auth.Permissions.Models.Permission", b =>
                {
                    b.Navigation("Aggregates");
                });

            modelBuilder.Entity("server.src.Domain.Auth.Roles.Models.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("server.src.Domain.Auth.Users.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("LogErrors");

                    b.Navigation("Stories");

                    b.Navigation("TelemetryRecords");

                    b.Navigation("UserClaims");

                    b.Navigation("UserLogins");

                    b.Navigation("UserLogouts");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("server.src.Domain.Developer.Aggreggates.Models.Aggregate", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("server.src.Domain.Developer.Features.Models.Feature", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("server.src.Domain.Developer.Modules.Models.Module", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.Continents.Models.Continent", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.Countries.Models.Country", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.Districts.Models.District", b =>
                {
                    b.Navigation("Neighborhoods");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.Municipalities.Models.Municipality", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.Neighborhoods.Models.Neighborhood", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.Regions.Models.Region", b =>
                {
                    b.Navigation("Municipalities");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Administrative.States.Models.State", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Natural.ClimateZones.Models.ClimateZone", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Natural.Locations.Models.Location", b =>
                {
                    b.Navigation("Forecasts");

                    b.Navigation("Observation");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Natural.NaturalFeatures.Models.NaturalFeature", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Natural.TerrainTypes.Models.TerrainType", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("server.src.Domain.Geography.Natural.Timezones.Models.Timezone", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("server.src.Domain.Metrics.AuditLogs.Models.AuditLog", b =>
                {
                    b.Navigation("Trails");
                });

            modelBuilder.Entity("server.src.Domain.Metrics.TelemetryRecords.Models.TelemetryRecord", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Stories");
                });

            modelBuilder.Entity("server.src.Domain.Weather.MoonPhases.Models.MoonPhase", b =>
                {
                    b.Navigation("Forecasts");

                    b.Navigation("Observations");
                });

            modelBuilder.Entity("server.src.Domain.Weather.Warnings.Models.Warning", b =>
                {
                    b.Navigation("Forecasts");
                });
#pragma warning restore 612, 618
        }
    }
}
